# Generated by Django 4.2 on 2025-08-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0002_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Login',
            new_name='LOGIN',
        ),
    ]
