# Generated by Django 4.2 on 2025-08-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0005_petfoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories_name', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='accessories_images/')),
            ],
        ),
    ]
