# Generated by Django 4.2 on 2025-08-29 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0006_petaccessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='LOGIN',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='pet_app.login'),
        ),
        migrations.AddField(
            model_name='petaccessories',
            name='LOGIN',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='pet_app.login'),
        ),
        migrations.AddField(
            model_name='petfoods',
            name='LOGIN',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='pet_app.login'),
        ),
    ]
