# Generated by Django 4.2 on 2025-08-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0007_pet_login_petaccessories_login_petfoods_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petaccessories',
            name='LOGIN',
        ),
        migrations.RemoveField(
            model_name='petfoods',
            name='LOGIN',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='PetAccessories',
        ),
        migrations.DeleteModel(
            name='PetFoods',
        ),
    ]
