# Generated by Django 4.2 on 2025-08-29 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0008_remove_petaccessories_login_remove_petfoods_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetFoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='food_images/')),
                ('REGISTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_app.register')),
            ],
        ),
        migrations.CreateModel(
            name='PetAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories_name', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='accessories_images/')),
                ('REGISTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_app.register')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='pet_images/')),
                ('REGISTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_app.register')),
            ],
        ),
    ]
